### ISSUE TITLE
弱弱的问下，关于docker push的相关问题

### ISSUE THREAD

**Issue by zning1994** [zhangpeihao/LearningDocker#6]
我在阿里云ECS测试的，`docker push <用户名>/<镜像名>`之后，结果报错，具体代码如下：

```
[root@XXX ~]# docker push <用户名>/<镜像名>

Do you really want to push to public registry? [y/n]: y
The push refers to a repository [docker.io/zning/testapache2] (len: 0)
0b34e018b176: Preparing
unauthorized: authentication required
```

请问这是操作不当还是因为没有科学上网的原因所造成的啊？（通过docker login登录没有任何问题，提示`login succeeded`。之前为了加速下载docker images，在此测试服务器上装了灵雀云的加速服务）

如百忙之中回答，不胜感激。

**Comment by zhangpeihao** [comment]
我没有走代理或者VPN，可以push到docker hub。
灵雀云没有用过，我一般用daocloud加速。
有问题可以加群：94585507

**Comment by zning1994** [comment]
好的👌感谢～
